Create Schema ccw2;
GO

Create Table ccw2.Products(
	ID int Not Null Primary Key Identity,
	Name Varchar(20) Not Null,
	Price Money Not Null
);

Create Table ccw2.Customers(
	ID int Not Null Primary Key Identity,
	FirstName VarChar(20) Not Null,
	LastName VarChar(20) Not Null,
	CardNumber Int
);

Create Table ccw2.Orders(
	ID int Not Null Primary Key Identity,
	ProductID int Not Null Foreign Key References ccw2.Products (ID),
	CustomerID int Not Null Foreign Key References ccw2.Customers (ID)
);

-- Add at least 3 records into each table.
Insert Into ccw2.Products (Name, Price) Values ('TV', $399.99), ('Nintendo Switch', $299.99), ('Animal Crossing', $59.99);
Insert Into ccw2.Customers (FirstName, LastName, CardNumber) Values ('Russell', 'Gehan', 123), ('Adam','Breceda', 456), ('Oscar', 'Galindo', 789);
Insert Into ccw2.Orders (ProductID, CustomerID) Values (1, 1), (2, 2), (3, 3);

-- Add product iPhone priced at $200.
Insert Into ccw2.Products (Name, Price) Values ('iPhone', $200);

-- Add customer Tina Smith.
Insert Into ccw2.Customers (FirstName, LastName) Values ('Tina', 'Smith');

-- Create order for Tina Smith bought an iPhone.
Insert Into ccw2.Orders (ProductID, CustomerID) Values ((Select ID From ccw2.Customers Where FirstName = 'Tina' AND LastName = 'Smith'), (Select ID From ccw2.Products Where Name = 'iPhone'));

-- Report all orders by Tina Smith.
Select ord.ID As OrderID, cus.ID As CustomerID, cus.FirstName, cus.LastName, pro.ID As ProductID, pro.Name As ProductName
From ccw2.Orders As ord, ccw2.Customers As cus, ccw2.Products as pro
Where ord.CustomerID = cus.ID AND ord.ProductID = pro.ID AND cus.FirstName = 'Tina' AND cus.LastName = 'Smith';

-- Report all revenue generated by sales of iPhone.
Select pro.Name, SUM(pro.Price) as Revenue
From ccw2.Products As pro, ccw2.Orders As ord
Where pro.ID = ord.ProductID AND pro.Name = 'iPhone'
Group By pro.Name; 

-- Increase the price of iPhone to $250.
Update ccw2.Products Set Price = (Select Price From ccw2.Products Where name = 'iPhone') + 250 Where Name = 'iPhone';